spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:guestbook}?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER:guest}
    password: ${DB_PASS:guestpw}
  sql:
    init:
      mode: always
      encoding: UTF-8
server:
  port: 8080
